// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txvwvxihvfltnidejfcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4dnd2eGlodmZsdG5pZGVqZmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTU4MDAsImV4cCI6MjA2NTczMTgwMH0.1LXM4c_q8ErJ5OAuKkxcJClGcoDNchq7fONjlW8RpPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);